//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub mod prelude;

pub mod permissions;
pub mod role_permissions;
pub mod roles;
pub mod sea_orm_active_enums;
pub mod user_roles;
pub mod users;
