//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub use super::permissions::Entity as Permissions;
pub use super::role_permissions::Entity as RolePermissions;
pub use super::roles::Entity as Roles;
pub use super::user_roles::Entity as UserRoles;
pub use super::users::Entity as Users;
