# dev.toml
[database]
url = "xxx" # 例如: "postgres://user:password@localhost/myapp"
init_sql = "init_db.sql"
max_connections = 100
min_connections = 5
connect_timeout = 10
acquire_timeout = 8
idle_timeout = 8
max_lifetime = 8
sqlx_logging = true

[server]
host = "localhost" # 例如: "127.0.0.1"
port = 8080 # 例如: 8080

# Redis 配置段
[redis]
host = "xxx" # Redis 服务器的地址
port = 6379         # Redis 服务器的端口，默认为 6379
password = "xxx"       # Redis 服务器的密码（如果有设置）
db = 0              # 默认数据库编号，从 0 开始

[jwt]
secret = "you-secret"
expire_time = 604800 #秒