//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub use super::sys_menu::Entity as SysMenu;
pub use super::sys_permission::Entity as SysPermission;
pub use super::sys_role::Entity as SysRole;
pub use super::sys_role_permission::Entity as SysRolePermission;
pub use super::sys_user::Entity as SysUser;
pub use super::sys_user_role::Entity as SysUserRole;
