//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.12

pub mod prelude;

pub mod sea_orm_active_enums;
pub mod sys_menu;
pub mod sys_menu_permission;
pub mod sys_permission;
pub mod sys_permission_action;
pub mod sys_role;
pub mod sys_role_permission;
pub mod sys_user;
pub mod sys_user_role;
