//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.12

use super::sea_orm_active_enums::ActionCode;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "sys_permission_action")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub permission_code: String,
    pub action_code: ActionCode,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::sys_permission::Entity",
        from = "Column::PermissionCode",
        to = "super::sys_permission::Column::PermissionCode",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    SysPermission,
}

impl Related<super::sys_permission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SysPermission.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
